name: code-quality-java

runs:
  using: composite
  steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup-java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - name: checkstyle with maven
      run: cd java-app; ./mvnw checkstyle:checkstyle
      shell: bash
    - name: checkstyle with maven
      run: cd java-app; ./mvnw test
      shell: bash
    - run: mkdir quality && cp -R target/reports/* quality && cp target/surefire-reports/* quality
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: Quality package
        path: java-app/quality

